---
- set_fact: epel_repo_rpm="install-2.11-1.el7.x86_64.rpm"

- name: check for epel RPM repo
  stat: path=/etc/yum.repos.d/epel.repo
  register: epel_repo_file

- name: copy repo RPM
  copy: src={{ epel_repo_rpm }} dest=/tmp/{{ epel_repo_rpm }}
  when: epel_repo_file.stat.exists == false

- name: install repo RPM
  yum: name=/tmp/{{ epel_repo_rpm }} state=present
  when: epel_repo_file.stat.exists == false

- name: remove rpm file
  file: path=/tmp/{{ epel_repo_rpm }} state=absent
  when: epel_repo_file.stat.exists == false

- name: install epel
  yum: name=epel-release.noarch state=present

