---
- name: install rpms
  yum: name=ejabberd-16.04-10.el7.centos state=present

- name: template ejabberd.yml
  template: src=ejabberd.yml.j2 dest=/etc/ejabberd/ejabberd.yml

- name: install ebin extensions
  copy: src="{{ item }}" dest="/usr/lib64/ejabberd-16.04/ebin/{{ item }}" owner=root group=root
  with_items:
    - mod_offline_post.beam
    - mod_ringmail.beam

- file: src=/usr/sbin/ejabberdctl dest=/usr/bin/ejabberdctl state=link

