# file: roles/mysql/tasks/main.yml
---
# install
- name: Check if mysql-community yum repo installed
  stat: path=/etc/yum.repos.d/mysql-community.repo
  register: check_mysql_repo

- command: "rpm -Uvh http://dev.mysql.com/get/mysql-community-release-el6-5.noarch.rpm"
  when: check_mysql_repo.stat.exists == false

- name: install mysql packages
  yum: name={{ item }} state=present
  with_items:
   - mysql-community-server
   - mysql-community-client
   - mysql-community-libs
   - mysql-community-libs-compat
   - mysql-community-devel
   - MySQL-python # CentOS mysql python stuff

# configure

- name: setup my.cnf
  template: >
    src=my.cnf.j2
    dest=/etc/my.cnf
    owner=mysql
    group=mysql
    mode=0644
  notify: restart mysql

- name: initialize mysql database
  command: creates=/var/lib/mysql/auto.cnf mysql_install_db --random-passwords

- name: start mysql service
  service: name=mysqld state=started enabled=yes

# secure

- name: save password for mysql root
  template: >
    dest=~root/.my.cnf
    src=root.my.cnf.j2
    owner=root
    group=root
    mode=0600

- name: check mysql initial password file exists.
  stat: path=/root/.mysql_secret
  register: st
  changed_when: False

- name: set mysql root password.
  script: set_root_password.sh
  when: st.stat.isreg is defined and st.stat.isreg == true

- name: secure mysql installation
  script: mysql_secure_installation.sh
  when: st.stat.isreg is defined and st.stat.isreg == true

- name: delete mysql initial password file.
  file: path=/root/.mysql_secret state=absent

